/** Tłumaczenia Control Center (hairqoo3) — PL + EN */
export const CC_DICT = {
  pl: {
    brand: "Hairqoo",
    tagline: "Globalny system operacyjny branży fryzjerskiej i barberskiej",
    hero: {
      title: "Wszystko, co fryzjerskie —",
      highlight: "znajdź, ucz się, twórz.",
      lead: "Globalna wyszukiwarka, asystent AI i spersonalizowany feed. Wydarzenia, edukatorzy, produkty i społeczność w jednym systemie.",
    },
    nav: {
      discover: "Odkrywaj",
      events: "Wydarzenia",
      calendar: "Kalendarz",
      map: "Mapa",
      education: "Edukacja",
      educators: "Edukatorzy",
      products: "Produkty",
      community: "Społeczność",
      career: "Kariera",
      tv: "Hairqoo TV",
      awards: "Nagrody",
      passport: "Paszport",
    },
    search: {
      placeholder: "Szukaj wydarzeń, edukatorów, produktów, technik…",
      trending: "Na czasie",
      submit: "Szukaj",
    },
    ai: {
      title: "Asystent AI",
      subtitle: "Zapytaj naturalnym językiem — znajdę wydarzenia, edukatorów i produkty.",
      open: "Otwórz asystenta AI",
      prompts: [
        "Kursy balayage w Polsce w tym miesiącu",
        "Top edukatorzy barberingu",
        "Najlepiej oceniane maszynki do fade",
        "Wydarzenia fryzjerskie blisko mnie",
      ],
    },
    portals: {
      businessHeadline: "Twój biznes",
      clientHeadline: "Twoje wizyty",
      salonTitle: "Portal Fryzjera",
      salonDesc: "Zajrzyj do środka i zobacz, jak wygląda Twój dzień pracy w salonie.",
      salonCta: "Startuję tour salonu →",
      clientTitle: "Portal Klienta",
      clientDesc: "Umów wizytę w kilka kliknięć i trzymaj swoje terminy pod kontrolą.",
      clientCta: "Wchodzę jako klient →",
    },
    sections: {
      discover: "Odkrywaj",
      discoverSub: "Spersonalizowany feed: wydarzenia, edukatorzy, produkty i techniki.",
      trending: "Na czasie",
      trendingSub: "Rosnące techniki, edukatorzy i wiralowe produkty.",
      events: "Globalne wydarzenia",
      eventsSub: "Najbliższe i wyróżnione wydarzenia z całego świata.",
      calendar: "Globalny kalendarz fryzjerski",
      calendarSub: "Pokazy, szkolenia i premiery w jednym miejscu.",
      map: "Mapa świata Hairqoo",
      mapSub: "Edukatorzy, wydarzenia, salony i akademie na mapie.",
      education: "Hub edukacyjny",
      educationSub: "Kursy, masterclassy, certyfikaty i warsztaty.",
      educators: "Top edukatorzy",
      educatorsSub: "Ranking z HairQoo Score i weryfikacją.",
      products: "Centrum produktów",
      productsSub: "Nowości, trendy i najlepiej oceniane narzędzia.",
      community: "Społeczność",
      communitySub: "Q&A, case studies, metamorfozy i biznes.",
      career: "Centrum kariery",
      careerSub: "Oferty pracy, staże i rekrutacja w salonach.",
      tv: "Hairqoo TV",
      tvSub: "Wywiady, tutoriale, relacje z wydarzeń i premiery.",
      awards: "Hairqoo Awards",
      awardsSub: "Głosowanie, kategorie i rankingi branży.",
      passport: "Hairqoo Passport",
      passportSub: "Twoja oś czasu kariery: certyfikaty, wydarzenia, osiągnięcia.",
      seeAll: "Zobacz wszystko",
    },
    newsletter: {
      title: "Bądź na bieżąco",
      desc: "Dołącz do newslettera Hairqoo — trendy, wydarzenia i premiery prosto na maila.",
      placeholder: "Twój adres e-mail",
      cta: "Zapisz mnie",
      success: "Dzięki! Sprawdź skrzynkę.",
    },
    footer: {
      product: "Produkt",
      company: "Firma",
      legal: "Prawne",
      language: "Język",
      rights: "Wszelkie prawa zastrzeżone.",
      privacy: "Prywatność",
      terms: "Regulamin",
      cookies: "Cookies",
    },
    common: { loading: "Ładowanie…", verified: "Zweryfikowane" },
    feed: { end: "To wszystko na teraz ✦" },
    calendar: { month: "Miesiąc", week: "Tydzień", year: "Rok" },
    awards: {
      educatorOfYear: "Edukator Roku",
      eventOfYear: "Wydarzenie Roku",
      productOfYear: "Produkt Roku",
      vote: "Zagłosuj",
      voted: "Zagłosowano ✓",
    },
    career: {
      roles: ["Stylista koloru", "Barber", "Edukator", "Recepcja / manager"],
      apply: "Aplikuj →",
    },
    map: { ecosystemLabel: "Ekosystem wg krajów" },
    passport: {
      items: [
        { year: "2026", label: "Certyfikat: Balayage Master" },
        { year: "2025", label: "Hairqoo World Summit — uczestnik" },
        { year: "2025", label: "Warsztat: Precyzyjne cięcia" },
        { year: "2024", label: "Dołączenie do Hairqoo" },
      ],
    },
    entityTypes: {
      event: "Wydarzenie",
      educator: "Edukator",
      product: "Produkt",
      academy: "Akademia",
      salon: "Salon",
      brand: "Marka",
      post: "Post",
      video: "Wideo",
    },
    layout: { homeTab: "Start", mobileNav: "Nawigacja mobilna", mainNav: "Główna nawigacja" },
  },
  en: {
    brand: "Hairqoo",
    tagline: "Global operating system for the hair & barber industry",
    hero: {
      title: "Everything hair —",
      highlight: "discover, learn, create.",
      lead: "Global search, AI assistant and personalised feed. Events, educators, products and community in one system.",
    },
    nav: {
      discover: "Discover",
      events: "Events",
      calendar: "Calendar",
      map: "Map",
      education: "Education",
      educators: "Educators",
      products: "Products",
      community: "Community",
      career: "Career",
      tv: "Hairqoo TV",
      awards: "Awards",
      passport: "Passport",
    },
    search: {
      placeholder: "Search events, educators, products, techniques…",
      trending: "Trending",
      submit: "Search",
    },
    ai: {
      title: "AI Assistant",
      subtitle: "Ask in natural language — I'll find events, educators and products.",
      open: "Open AI assistant",
      prompts: [
        "Balayage courses in Poland this month",
        "Top barbering educators",
        "Highest-rated fade clippers",
        "Hair events near me",
      ],
    },
    portals: {
      businessHeadline: "Your business",
      clientHeadline: "Your visits",
      salonTitle: "Stylist Portal",
      salonDesc: "Step inside and see what your day at the salon looks like.",
      salonCta: "Start salon tour →",
      clientTitle: "Client Portal",
      clientDesc: "Book in a few taps and keep your appointments under control.",
      clientCta: "Enter as client →",
    },
    sections: {
      discover: "Discover",
      discoverSub: "Personalised feed: events, educators, products and techniques.",
      trending: "Trending now",
      trendingSub: "Rising techniques, educators and viral products.",
      events: "Global events",
      eventsSub: "Nearest and featured events worldwide.",
      calendar: "Global hair calendar",
      calendarSub: "Shows, training and launches in one place.",
      map: "Hairqoo world map",
      mapSub: "Educators, events, salons and academies on the map.",
      education: "Education hub",
      educationSub: "Courses, masterclasses, certifications and workshops.",
      educators: "Top educators",
      educatorsSub: "Ranking with HairQoo Score and verification.",
      products: "Product centre",
      productsSub: "Launches, trends and top-rated tools.",
      community: "Community",
      communitySub: "Q&A, case studies, transformations and business.",
      career: "Career centre",
      careerSub: "Jobs, internships and salon hiring.",
      tv: "Hairqoo TV",
      tvSub: "Interviews, tutorials, event coverage and launches.",
      awards: "Hairqoo Awards",
      awardsSub: "Voting, categories and industry rankings.",
      passport: "Hairqoo Passport",
      passportSub: "Your career timeline: certificates, events, achievements.",
      seeAll: "See all",
    },
    newsletter: {
      title: "Stay in the loop",
      desc: "Join the Hairqoo newsletter — trends, events and launches in your inbox.",
      placeholder: "Your email address",
      cta: "Sign me up",
      success: "Thanks! Check your inbox.",
    },
    footer: {
      product: "Product",
      company: "Company",
      legal: "Legal",
      language: "Language",
      rights: "All rights reserved.",
      privacy: "Privacy",
      terms: "Terms",
      cookies: "Cookies",
    },
    common: { loading: "Loading…", verified: "Verified" },
    feed: { end: "That's all for now ✦" },
    calendar: { month: "Month", week: "Week", year: "Year" },
    awards: {
      educatorOfYear: "Educator of the Year",
      eventOfYear: "Event of the Year",
      productOfYear: "Product of the Year",
      vote: "Vote",
      voted: "Voted ✓",
    },
    career: {
      roles: ["Colour stylist", "Barber", "Educator", "Reception / manager"],
      apply: "Apply →",
    },
    map: { ecosystemLabel: "Ecosystem by country" },
    passport: {
      items: [
        { year: "2026", label: "Certificate: Balayage Master" },
        { year: "2025", label: "Hairqoo World Summit — attendee" },
        { year: "2025", label: "Workshop: Precision cutting" },
        { year: "2024", label: "Joined Hairqoo" },
      ],
    },
    entityTypes: {
      event: "Event",
      educator: "Educator",
      product: "Product",
      academy: "Academy",
      salon: "Salon",
      brand: "Brand",
      post: "Post",
      video: "Video",
    },
    layout: { homeTab: "Home", mobileNav: "Mobile navigation", mainNav: "Main navigation" },
  },
};

export function getCcDict(lang) {
  return CC_DICT[lang] ?? CC_DICT.en ?? CC_DICT.pl;
}
