/** Tłumaczenia Control Center (hairqoo3) — PL, EN, ES, FR, PT */
import es from "./cc-locales/es.js?version=6.6.0";
import fr from "./cc-locales/fr.js?version=6.6.0";
import pt from "./cc-locales/pt.js?version=6.6.0";

export const CC_DICT = {
  pl: {
    brand: "Hairqoo",
    tagline: "Globalny system operacyjny branży fryzjerskiej i barberskiej",
    hero: {
      title: "Wszystko, co fryzjerskie —",
      highlight: "znajdź, ucz się, twórz.",
      lead: "Globalna wyszukiwarka, asystent AI i spersonalizowany feed. Wydarzenia, edukatorzy, produkty i społeczność w jednym systemie.",
    },
    nav: {
      discover: "Odkrywaj",
      events: "Wydarzenia",
      calendar: "Kalendarz",
      map: "Mapa",
      education: "Edukacja",
      educators: "Edukatorzy",
      products: "Produkty",
      community: "Społeczność",
      career: "Kariera",
      tv: "Hairqoo TV",
      awards: "Nagrody",
      passport: "Paszport",
    },
    search: {
      placeholder: "Szukaj wydarzeń, edukatorów, produktów, technik…",
      placeholderShort: "Szukaj…",
      trending: "Na czasie",
      submit: "Szukaj",
      voice: "Wyszukiwanie głosowe",
      voiceListening: "Słucham…",
      voiceDenied: "Brak dostępu do mikrofonu",
      allResults: "Wszystkie wyniki",
      noResults: "Brak wyników",
      resultsFor: "Wyniki dla",
    },
    ai: {
      title: "Asystent AI",
      subtitle: "Zapytaj naturalnym językiem — znajdę wydarzenia, edukatorów i produkty.",
      placeholder: "np. Pokaż kursy balayage w Polsce w tym miesiącu",
      send: "Wyślij",
      open: "Otwórz asystenta AI",
      thinking: "Analizuję…",
      suggestionsTitle: "Sugestie",
      prompts: [
        "Kursy balayage w Polsce w tym miesiącu",
        "Top edukatorzy barberingu",
        "Najlepiej oceniane maszynki do fade",
        "Wydarzenia fryzjerskie blisko mnie",
      ],
    },
    aiVisibility: {
      whySeeing: "Dlaczego to widzę?",
      rankingTitle: "Wyjaśnienie rankingu AI",
      rankingLead: "Podgląd score breakdown dla najlepszego dopasowania (tylko odczyt).",
      panelTitle: "Ranking AI",
      hairQooScore: "HairQoo Score",
      verified: "Status weryfikacji",
      verifiedYes: "Zweryfikowany",
      verifiedNo: "Niezweryfikowany",
      popularity: "Popularność",
      countryBoost: "Boost kraju",
      recencyBoost: "Boost świeżości",
      brainNodes: "Węzły grafu",
    },
    portals: {
      businessHeadline: "Twój biznes",
      clientHeadline: "Twoje wizyty",
      salonTitle: "Portal Fryzjera",
      salonDesc: "Zajrzyj do środka i zobacz, jak wygląda Twój dzień pracy w salonie.",
      salonCta: "Startuję tour salonu →",
      clientTitle: "Portal Klienta",
      clientDesc: "Umów wizytę w kilka kliknięć i trzymaj swoje terminy pod kontrolą.",
      clientCta: "Wchodzę jako klient →",
    },
    sections: {
      discover: "Odkrywaj",
      discoverSub: "Spersonalizowany feed: wydarzenia, edukatorzy, produkty i techniki.",
      trending: "Na czasie",
      trendingSub: "Rosnące techniki, edukatorzy i wiralowe produkty.",
      events: "Globalne wydarzenia",
      eventsSub: "Najbliższe i wyróżnione wydarzenia z całego świata.",
      calendar: "Globalny kalendarz fryzjerski",
      calendarSub: "Pokazy, szkolenia i premiery w jednym miejscu.",
      map: "Mapa świata Hairqoo",
      mapSub: "Edukatorzy, wydarzenia, salony i akademie na mapie.",
      education: "Hub edukacyjny",
      educationSub: "Kursy, masterclassy, certyfikaty i warsztaty.",
      educators: "Top edukatorzy",
      educatorsSub: "Ranking z HairQoo Score i weryfikacją.",
      products: "Centrum produktów",
      productsSub: "Nowości, trendy i najlepiej oceniane narzędzia.",
      community: "Społeczność",
      communitySub: "Q&A, case studies, metamorfozy i biznes.",
      career: "Centrum kariery",
      careerSub: "Oferty pracy, staże i rekrutacja w salonach.",
      tv: "Hairqoo TV",
      tvSub: "Wywiady, tutoriale, relacje z wydarzeń i premiery.",
      awards: "Hairqoo Awards",
      awardsSub: "Głosowanie, kategorie i rankingi branży.",
      passport: "Hairqoo Passport",
      passportSub: "Twoja oś czasu kariery: certyfikaty, wydarzenia, osiągnięcia.",
      seeAll: "Zobacz wszystko",
    },
    newsletter: {
      title: "Bądź na bieżąco",
      desc: "Dołącz do newslettera Hairqoo — trendy, wydarzenia i premiery prosto na maila.",
      placeholder: "Twój adres e-mail",
      cta: "Zapisz mnie",
      success: "Dzięki! Sprawdź skrzynkę.",
    },
    footer: {
      product: "Produkt",
      company: "Firma",
      legal: "Prawne",
      language: "Język",
      rights: "Wszelkie prawa zastrzeżone.",
      privacy: "Prywatność",
      terms: "Regulamin",
      cookies: "Cookies",
    },
    common: {
      loading: "Ładowanie…",
      verified: "Zweryfikowane",
      backHome: "Wróć na stronę główną",
      country: "Kraj",
      allCountries: "Wszystkie kraje",
      noFilterResults: "Brak wyników dla wybranych filtrów.",
      similar: "Podobne",
      close: "Zamknij",
      profile: "Profil",
      items: "pozycji",
    },
    feed: { end: "To wszystko na teraz ✦" },
    calendar: { month: "Miesiąc", week: "Tydzień", year: "Rok" },
    awards: {
      educatorOfYear: "Edukator Roku",
      eventOfYear: "Wydarzenie Roku",
      productOfYear: "Produkt Roku",
      vote: "Zagłosuj",
      voted: "Zagłosowano ✓",
    },
    career: {
      roles: ["Stylista koloru", "Barber", "Edukator", "Recepcja / manager"],
      apply: "Aplikuj →",
    },
    map: { ecosystemLabel: "Ekosystem wg krajów" },
    passport: {
      levelLabel: "Poziom",
      toNext: "Do następnego poziomu",
      events: "Wydarzenia",
      education: "Edukacja",
      achievements: "Osiągnięcia",
      awards: "Nagrody",
      empty: "Twój passport zacznie się wypełniać po interakcjach z ekosystemem HairQoo.",
      items: [],
    },
    entityTypes: {
      event: "Wydarzenie",
      educator: "Edukator",
      product: "Produkt",
      academy: "Akademia",
      salon: "Salon",
      brand: "Marka",
      post: "Post",
      video: "Wideo",
      user: "Użytkownik",
    },
    profile: {
      label: "Profil",
      itemsInEcosystem: "pozycji w ekosystemie Hairqoo",
    },
    errors: {
      searchFailed: "Nie udało się wyszukać. Spróbuj ponownie.",
      aiFailed: "Coś poszło nie tak. Spróbuj ponownie.",
      aiNoMatch: "Nie znalazłem dopasowań — spróbuj doprecyzować zapytanie.",
    },
    aiAnswers: {
      found: "Znalazłem {count} dopasowanych pozycji ({type}). Oto najlepsze propozycje:",
      foundOne: "Znalazłem 1 dopasowaną pozycję ({type}). Oto najlepsza propozycja:",
      typeEvent: "wydarzenia",
      typeEducator: "edukatorzy",
      typeProduct: "produkty",
      typeVideo: "wideo",
      typeDefault: "wyniki",
      allResults: "Wszystkie wyniki",
      eventsLink: "Wydarzenia",
      educatorsLink: "Edukatorzy",
      productsLink: "Produkty",
    },
    layout: { homeTab: "Start", mobileNav: "Nawigacja mobilna", mainNav: "Główna nawigacja" },
  },
  en: {
    brand: "Hairqoo",
    tagline: "Global operating system for the hair & barber industry",
    hero: {
      title: "Everything hair —",
      highlight: "discover, learn, create.",
      lead: "Global search, AI assistant and personalised feed. Events, educators, products and community in one system.",
    },
    nav: {
      discover: "Discover",
      events: "Events",
      calendar: "Calendar",
      map: "Map",
      education: "Education",
      educators: "Educators",
      products: "Products",
      community: "Community",
      career: "Career",
      tv: "Hairqoo TV",
      awards: "Awards",
      passport: "Passport",
    },
    search: {
      placeholder: "Search events, educators, products, techniques…",
      placeholderShort: "Search…",
      trending: "Trending",
      submit: "Search",
      voice: "Voice search",
      voiceListening: "Listening…",
      voiceDenied: "Microphone access denied",
      allResults: "All results",
      noResults: "No results",
      resultsFor: "Results for",
    },
    ai: {
      title: "AI Assistant",
      subtitle: "Ask in natural language — I'll find events, educators and products.",
      placeholder: "e.g. Show balayage courses in Poland this month",
      send: "Send",
      open: "Open AI assistant",
      thinking: "Analysing…",
      suggestionsTitle: "Suggestions",
      prompts: [
        "Balayage courses in Poland this month",
        "Top barbering educators",
        "Highest-rated fade clippers",
        "Hair events near me",
      ],
    },
    aiVisibility: {
      whySeeing: "Why am I seeing this?",
      rankingTitle: "AI ranking explanation",
      rankingLead: "Score breakdown preview for the top match (read-only).",
      panelTitle: "AI ranking",
      hairQooScore: "HairQoo Score",
      verified: "Verified status",
      verifiedYes: "Verified",
      verifiedNo: "Unverified",
      popularity: "Popularity",
      countryBoost: "Country boost",
      recencyBoost: "Recency boost",
      brainNodes: "Graph nodes",
    },
    portals: {
      businessHeadline: "Your business",
      clientHeadline: "Your visits",
      salonTitle: "Stylist Portal",
      salonDesc: "Step inside and see what your day at the salon looks like.",
      salonCta: "Start salon tour →",
      clientTitle: "Client Portal",
      clientDesc: "Book in a few taps and keep your appointments under control.",
      clientCta: "Enter as client →",
    },
    sections: {
      discover: "Discover",
      discoverSub: "Personalised feed: events, educators, products and techniques.",
      trending: "Trending now",
      trendingSub: "Rising techniques, educators and viral products.",
      events: "Global events",
      eventsSub: "Nearest and featured events worldwide.",
      calendar: "Global hair calendar",
      calendarSub: "Shows, training and launches in one place.",
      map: "Hairqoo world map",
      mapSub: "Educators, events, salons and academies on the map.",
      education: "Education hub",
      educationSub: "Courses, masterclasses, certifications and workshops.",
      educators: "Top educators",
      educatorsSub: "Ranking with HairQoo Score and verification.",
      products: "Product centre",
      productsSub: "Launches, trends and top-rated tools.",
      community: "Community",
      communitySub: "Q&A, case studies, transformations and business.",
      career: "Career centre",
      careerSub: "Jobs, internships and salon hiring.",
      tv: "Hairqoo TV",
      tvSub: "Interviews, tutorials, event coverage and launches.",
      awards: "Hairqoo Awards",
      awardsSub: "Voting, categories and industry rankings.",
      passport: "Hairqoo Passport",
      passportSub: "Your career timeline: certificates, events, achievements.",
      seeAll: "See all",
    },
    newsletter: {
      title: "Stay in the loop",
      desc: "Join the Hairqoo newsletter — trends, events and launches in your inbox.",
      placeholder: "Your email address",
      cta: "Sign me up",
      success: "Thanks! Check your inbox.",
    },
    footer: {
      product: "Product",
      company: "Company",
      legal: "Legal",
      language: "Language",
      rights: "All rights reserved.",
      privacy: "Privacy",
      terms: "Terms",
      cookies: "Cookies",
    },
    common: {
      loading: "Loading…",
      verified: "Verified",
      backHome: "Back to home",
      country: "Country",
      allCountries: "All countries",
      noFilterResults: "No results for selected filters.",
      similar: "Similar",
      close: "Close",
      profile: "Profile",
      items: "items",
    },
    feed: { end: "That's all for now ✦" },
    calendar: { month: "Month", week: "Week", year: "Year" },
    awards: {
      educatorOfYear: "Educator of the Year",
      eventOfYear: "Event of the Year",
      productOfYear: "Product of the Year",
      vote: "Vote",
      voted: "Voted ✓",
    },
    career: {
      roles: ["Colour stylist", "Barber", "Educator", "Reception / manager"],
      apply: "Apply →",
    },
    map: { ecosystemLabel: "Ecosystem by country" },
    passport: {
      levelLabel: "Level",
      toNext: "To next level",
      events: "Events",
      education: "Education",
      achievements: "Achievements",
      awards: "Awards",
      empty: "Your passport will fill in as you interact with the HairQoo ecosystem.",
      items: [],
    },
    entityTypes: {
      event: "Event",
      educator: "Educator",
      product: "Product",
      academy: "Academy",
      salon: "Salon",
      brand: "Brand",
      post: "Post",
      video: "Video",
      user: "User",
    },
    profile: {
      label: "Profile",
      itemsInEcosystem: "items in the Hairqoo ecosystem",
    },
    errors: {
      searchFailed: "Search failed. Please try again.",
      aiFailed: "Something went wrong. Please try again.",
      aiNoMatch: "No matches found — try refining your query.",
    },
    aiAnswers: {
      found: "I found {count} matching items ({type}). Here are the best picks:",
      foundOne: "I found 1 matching item ({type}). Here's the best pick:",
      typeEvent: "events",
      typeEducator: "educators",
      typeProduct: "products",
      typeVideo: "videos",
      typeDefault: "results",
      allResults: "All results",
      eventsLink: "Events",
      educatorsLink: "Educators",
      productsLink: "Products",
    },
    layout: { homeTab: "Home", mobileNav: "Mobile navigation", mainNav: "Main navigation" },
  },
  es,
  fr,
  pt,
};

export function getCcDict(lang) {
  return CC_DICT[lang] ?? CC_DICT.en ?? CC_DICT.pl;
}
